-- ============================================================
-- Seed: PhilosoRaptors song catalog
-- Run in the Supabase SQL editor.
-- Uses the first band in the bands table as the target.
-- Skips duplicates (title + band_id) on conflict.
-- ============================================================

do $$
declare
  v_band_id uuid;
begin
  select id into v_band_id from public.bands limit 1;

  insert into public.songs (band_id, title, artist, status)
  values
    (v_band_id, 'Amber', '311', 'ready'),
    (v_band_id, 'Beautiful Disaster', '311', 'ready'),
    (v_band_id, 'Kryptonite', '3 Doors Down', 'ready'),
    (v_band_id, 'Team America', '66samus', 'ready'),
    (v_band_id, 'I Ran (So Far Away)', 'A Flock Of Seagulls', 'ready'),
    (v_band_id, 'Smooth Criminal', 'Alien Ant Farm', 'ready'),
    (v_band_id, 'Be Yourself', 'Audioslave', 'ready'),
    (v_band_id, 'Cochise', 'Audioslave', 'ready'),
    (v_band_id, 'Gasoline', 'Audioslave', 'ready'),
    (v_band_id, 'Fuck You', 'Bad Religion', 'ready'),
    (v_band_id, 'Ain''t No Sunshine', 'Bill Withers', 'ready'),
    (v_band_id, 'Rebel Yell', 'Billy Idol', 'ready'),
    (v_band_id, 'White Wedding', 'Billy Idol', 'ready'),
    (v_band_id, 'Let''s Get It Started', 'Black Eyed Peas', 'ready'),
    (v_band_id, 'Paranoid', 'Black Sabbath', 'ready'),
    (v_band_id, 'All The Small Things', 'blink-182', 'ready'),
    (v_band_id, 'Carousel', 'blink-182', 'ready'),
    (v_band_id, 'Three Little Birds', 'Bob Marley & The Wailers', 'ready'),
    (v_band_id, 'Wanted Dead or Alive', 'Bon Jovi', 'ready'),
    (v_band_id, 'More than a Feeling', 'Boston', 'ready'),
    (v_band_id, '1985', 'Bowling for Soup', 'ready'),
    (v_band_id, 'UpTown Funk', 'Bruno Mars', 'ready'),
    (v_band_id, 'The Distance', 'CAKE', 'ready'),
    (v_band_id, 'Tennessee Whiskey', 'Chris Stapleton', 'ready'),
    (v_band_id, 'Where The River Flows', 'Collective Soul', 'ready'),
    (v_band_id, 'Shine', 'Collective Soul', 'ready'),
    (v_band_id, 'Brick House', 'Commodores', 'ready'),
    (v_band_id, 'Crossroads', 'Cream', 'ready'),
    (v_band_id, 'Torn', 'Creed', 'ready'),
    (v_band_id, 'One Last Breath', 'Creed', 'ready'),
    (v_band_id, 'Have You Ever Seen The Rain', 'Creedence Clearwater Revival', 'ready'),
    (v_band_id, 'You Spin Me Round (Like a Record)', 'Dead Or Alive', 'ready'),
    (v_band_id, 'Doors Unlocked and Open', 'Death Cab for Cutie', 'ready'),
    (v_band_id, 'Shout 2000', 'Disturbed', 'ready'),
    (v_band_id, 'Drift Away', 'Dobie Gray', 'ready'),
    (v_band_id, 'Cake By The Ocean', 'DNCE', 'ready'),
    (v_band_id, 'I''m Shipping Up To Boston', 'Dropkick Murphys', 'ready'),
    (v_band_id, 'Blue (Da Ba Dee)', 'Eiffel 65', 'ready'),
    (v_band_id, 'Sweet Home Chicago', 'Eric Clapton', 'ready'),
    (v_band_id, 'Dreams', 'Fleetwood Mac', 'ready'),
    (v_band_id, 'Slow Ride', 'Foghat', 'ready'),
    (v_band_id, 'Everlong', 'Foo Fighters', 'ready'),
    (v_band_id, 'Monkey Wrench', 'Foo Fighters', 'ready'),
    (v_band_id, 'Stacy''s Mom', 'Fountains Of Wayne', 'ready'),
    (v_band_id, 'Take Me Out', 'Franz Ferdinand', 'ready'),
    (v_band_id, 'Pony', 'Ginuwine', 'ready'),
    (v_band_id, 'Basket Case', 'Green Day', 'ready'),
    (v_band_id, 'Holiday', 'Green Day', 'ready'),
    (v_band_id, 'Brain Stew/Jaded', 'Green Day', 'ready'),
    (v_band_id, 'American Idiot', 'Green Day', 'ready'),
    (v_band_id, 'Alone', 'Heart', 'ready'),
    (v_band_id, 'Lydia', 'Highly Suspect', 'ready'),
    (v_band_id, 'Wicked Game', 'HIM', 'ready'),
    (v_band_id, 'Drive', 'Incubus', 'ready'),
    (v_band_id, 'Make Yourself', 'Incubus', 'ready'),
    (v_band_id, 'Privilege', 'Incubus', 'ready'),
    (v_band_id, 'Are You Gonna Be My Girl', 'Jet', 'ready'),
    (v_band_id, 'Fire', 'Jimi Hendrix', 'ready'),
    (v_band_id, 'Foxey Lady', 'Jimi Hendrix', 'ready'),
    (v_band_id, 'Hey Joe', 'Jimi Hendrix', 'ready'),
    (v_band_id, 'The Middle', 'Jimmy Eat World', 'ready'),
    (v_band_id, 'I Love Rock ''N Roll', 'Joan Jett & the Blackhearts', 'ready'),
    (v_band_id, 'Take Me Home, Country Roads', 'John Denver', 'ready'),
    (v_band_id, 'Slow Dancing in a Burning Room', 'John Mayer', 'ready'),
    (v_band_id, 'Danger Zone', 'Kenny Loggins', 'ready'),
    (v_band_id, 'Blue on Black', 'Kenny Wayne Shepherd', 'ready'),
    (v_band_id, 'Good Times Bad Times', 'Led Zeppelin', 'ready'),
    (v_band_id, 'Fly Away', 'Lenny Kravitz', 'ready'),
    (v_band_id, 'Ring of Fire', 'Lera Lynn', 'ready'),
    (v_band_id, 'Nookie', 'Limp Bizkit', 'ready'),
    (v_band_id, 'My Own Worst Enemy', 'Lit', 'ready'),
    (v_band_id, 'Scotty Doesn''t Know', 'Lustra', 'ready'),
    (v_band_id, 'Rude', 'Magic!', 'ready'),
    (v_band_id, 'This Love', 'Maroon 5', 'ready'),
    (v_band_id, 'Let''s Get It On', 'Marvin Gaye', 'ready'),
    (v_band_id, 'Fuel', 'Metallica', 'ready'),
    (v_band_id, 'Mississippi Queen', 'Mountain', 'ready'),
    (v_band_id, 'Panic Station', 'Muse', 'ready'),
    (v_band_id, 'Hysteria', 'Muse', 'ready'),
    (v_band_id, 'Sweet Caroline', 'Neil Diamond', 'ready'),
    (v_band_id, 'How You Remind Me', 'Nickelback', 'ready'),
    (v_band_id, 'In Bloom', 'Nirvana', 'ready'),
    (v_band_id, 'Hey Ya!', 'Outkast', 'ready'),
    (v_band_id, 'Last Resort', 'Papa Roach', 'ready'),
    (v_band_id, 'All I Wanted', 'Paramore', 'ready'),
    (v_band_id, 'Jeremy', 'Pearl Jam', 'ready'),
    (v_band_id, 'Hey You', 'Pink Floyd', 'ready'),
    (v_band_id, 'I Had Some Help', 'Post Malone', 'ready'),
    (v_band_id, 'She Hates Me', 'Puddle of Mudd', 'ready'),
    (v_band_id, 'Creep', 'Radiohead', 'ready'),
    (v_band_id, 'Killing In The Name', 'Rage Against The Machine', 'ready'),
    (v_band_id, 'Testify', 'Rage Against The Machine', 'ready'),
    (v_band_id, 'Bulls On Parade', 'Rage Against The Machine', 'ready'),
    (v_band_id, 'Can''t Stop', 'Red Hot Chili Peppers', 'ready'),
    (v_band_id, 'Soul to Squeeze', 'Red Hot Chili Peppers', 'ready'),
    (v_band_id, 'Otherside', 'Red Hot Chili Peppers', 'ready'),
    (v_band_id, 'Dani California', 'Red Hot Chili Peppers', 'ready'),
    (v_band_id, 'By the Way', 'Red Hot Chili Peppers', 'ready'),
    (v_band_id, 'Around the World', 'Red Hot Chili Peppers', 'ready'),
    (v_band_id, 'Suck My Kiss', 'Red Hot Chili Peppers', 'ready'),
    (v_band_id, 'Rock You Like A Hurricane', 'Scorpions', 'ready'),
    (v_band_id, 'Cumbersome', 'Seven Mary Three', 'ready'),
    (v_band_id, 'Walkin'' on the Sun', 'Smash Mouth', 'ready'),
    (v_band_id, 'Fell On Black Days', 'Soundgarden', 'ready'),
    (v_band_id, 'Pride and Joy', 'Stevie Ray Vaughan', 'ready'),
    (v_band_id, 'Superstition', 'Stevie Wonder', 'ready'),
    (v_band_id, 'Plush', 'Stone Temple Pilots', 'ready'),
    (v_band_id, 'Smoke Two Joints', 'Sublime', 'ready'),
    (v_band_id, 'Santeria', 'Sublime', 'ready'),
    (v_band_id, 'Caress Me Down', 'Sublime', 'ready'),
    (v_band_id, 'What I Got', 'Sublime', 'ready'),
    (v_band_id, 'This Is Your Life', 'Switchfoot', 'ready'),
    (v_band_id, 'Love Story', 'Taylor Swift', 'ready'),
    (v_band_id, 'While My Guitar Gently Weeps', 'The Beatles', 'ready'),
    (v_band_id, 'Come Together', 'The Beatles', 'ready'),
    (v_band_id, 'Just What I Needed', 'The Cars', 'ready'),
    (v_band_id, 'Zombie', 'The Cranberries', 'ready'),
    (v_band_id, 'I Believe in a Thing Called Love', 'The Darkness', 'ready'),
    (v_band_id, 'Long Train Runnin''', 'The Doobie Brothers', 'ready'),
    (v_band_id, 'Roadhouse Blues', 'The Doors', 'ready'),
    (v_band_id, 'Mr. Brightside', 'The Killers', 'ready'),
    (v_band_id, 'White on the Ground', 'The Kruse Brothers', 'ready'),
    (v_band_id, 'Can''t You See', 'The Marshall Tucker Band', 'ready'),
    (v_band_id, 'Reptilia', 'The Strokes', 'ready'),
    (v_band_id, 'Seven Nation Army', 'The White Stripes', 'ready'),
    (v_band_id, 'Jumper', 'Third Eye Blind', 'ready'),
    (v_band_id, 'You Wreck Me', 'Tom Petty', 'ready'),
    (v_band_id, 'American Girl', 'Tom Petty and the Heartbreakers', 'ready'),
    (v_band_id, 'Give Me One Reason', 'Tracy Chapman', 'ready'),
    (v_band_id, 'Headstrong', 'Trapt', 'ready'),
    (v_band_id, 'Into the Mystic', 'Van Morrison', 'ready'),
    (v_band_id, 'Blister In The Sun', 'Violent Femmes', 'ready'),
    (v_band_id, 'Say It Ain''t So', 'Weezer', 'ready'),
    (v_band_id, 'Ocean Avenue', 'Yellowcard', 'ready'),
    (v_band_id, 'Tush', 'ZZ Top', 'ready')
  on conflict do nothing;

  raise notice 'Inserted songs for band: %', v_band_id;
end $$;
